on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  RUSTFLAGS: "-Awarnings"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            extension: ""
            name_suffix: linux
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            extension: ".exe"
            name_suffix: windows
          - os: macos-latest
            target: x86_64-apple-darwin
            extension: ""
            name_suffix: macos

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
          override: true

      - name: Build the binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Test the binary
        run: cargo test --release --target ${{ matrix.target }}

      - name: Rename binary for upload
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            mv target/${{ matrix.target }}/release/rustymotif.exe rustymotif-${{ matrix.name_suffix }}${{ matrix.extension }}
            mv target/${{ matrix.target }}/release/mixedmotif.exe mixedmotif-${{ matrix.name_suffix }}${{ matrix.extension }}
            mv target/${{ matrix.target }}/release/motif_summary.exe motif_summary-${{ matrix.name_suffix }}${{ matrix.extension }}
          else
            mv target/${{ matrix.target }}/release/rustymotif rustymotif-${{ matrix.name_suffix }}${{ matrix.extension }}
            mv target/${{ matrix.target }}/release/mixedmotif mixedmotif-${{ matrix.name_suffix }}${{ matrix.extension }}
            mv target/${{ matrix.target }}/release/motif_summary motif_summary-${{ matrix.name_suffix }}${{ matrix.extension }}
          fi
        shell: bash

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: rustymotif-${{ matrix.name_suffix }}
          path: rustymotif-${{ matrix.name_suffix }}${{ matrix.extension }}

      - name: Upload binary_mixedmotif
        uses: actions/upload-artifact@v4
        with:
          name: mixedmotif-${{ matrix.name_suffix }}
          path: mixedmotif-${{ matrix.name_suffix }}${{ matrix.extension }}

      - name: Upload binary_motif_summary
        uses: actions/upload-artifact@v4
        with:
          name: motif_summary-${{ matrix.name_suffix }}
          path: motif_summary-${{ matrix.name_suffix }}${{ matrix.extension }}

  release:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Download Binaries
        uses: actions/download-artifact@v4
        with:
          pattern: rustymotif-*
          merge-multiple: true
          run-id: ${{ github.event.workflow_run_id }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          files: |
            rustymotif-linux
            rustymotif-windows.exe
            rustymotif-macos
            mixedmotif-linux
            mixedmotif-windows.exe
            mixedmotif-macos
            motif_summary-linux
            motif_summary-windows.exe
            motif_summary-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
